version: '3'

services:
  php-app:
    build:
      context: ./src
    ports:
      - "45679:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_USER: ctf
      MYSQL_PASSWORD: Password_K1nz
      MYSQL_DATABASE: Z0k3r_K1nz
      MYSQL_ROOT_PASSWORD: Password_K1nz
    volumes:
      - ./database/db.sql:/docker-entrypoint-initdb.d/db.sql
