FROM ghcr.io/puppeteer/puppeteer

WORKDIR /app
RUN mkdir -p /app/storage/db

COPY package.json package-lock.json /app/

USER pptruser
RUN npm ci

COPY index.ts tsconfig.json /app/
COPY static /app/static
COPY prisma /app/prisma
COPY storage/db/dev.db /app/storage/db/dev.db

RUN npx prisma generate

EXPOSE 8000

CMD ["npm", "start"]
