export memory memory(initial: 3, max: 0);

global g_a:int = 132672;

table T_a:funcref(min: 1, max: 1);

export function func(a:int, b:int):int {
  var c:int = g_a;
  var d:int = 32;
  var e:int = c - d;
  g_a = e;
  e[7]:int = a;
  e[6]:int = b;
  var f:int = 1024;
  var g:int = f;
  var h:int = 1024;
  var i:int = g + h;
  e[5]:int = i;
  var j:int = e[7]:int;
  var k:int = 1024;
  var l:int = k;
  var m:int = 512;
  var n:int = l + m;
  var o:int = n;
  var p:int = 1;
  var q:int = j << p;
  var r:ushort_ptr = o + q;
  var s:int = r[0];
  e[9]:short = s;
  var t:int = e[5]:int;
  var u:int = e[9]:ushort;
  var v:int = 16;
  var w:int = u << v;
  var x:int = w >> v;
  var y:int = t + x;
  e[3]:int = y;
  var z:int = 1024;
  var aa:int = z;
  var ba:int = 64;
  var ca:int = aa + ba;
  e[2]:int = ca;
  var da:int_ptr = e[3]:int;
  var ea:int = da[0];
  e[1]:int = ea;
  var fa:int = 24;
  var ga:int = e + fa;
  var ha:int = ga;
  var ia:int = e[2]:int;
  var ja:int = 4;
  f_g(ha, ja, ia);
  var ka:int = e[2]:int;
  var la:int = e[3]:int;
  var ma:int = 4;
  var na:int = la + ma;
  var oa:int = e[1]:int;
  var pa:int = 1024;
  var qa:int = pa;
  var ra:int = 40960;
  var sa:int = qa + ra;
  f_k(ka, na, oa, sa);
  var ta:int = e[1]:int;
  var ua:int = 32;
  var va:int = e + ua;
  g_a = va;
  return ta;
}

function f_b(a:int, b:int):int {
  var c:int = g_a;
  var d:int = 16;
  var e:int_ptr = c - d;
  e[3] = a;
  e[2] = b;
  var f:int = e[3];
  var g:int = e[2];
  var h:int = f << g;
  var i:int = e[3];
  var j:int = e[2];
  var k:int = 32;
  var l:int = k - j;
  var m:int = i >> l;
  var n:int = h | m;
  return n;
}

function f_c(a:int) {
  var b:int = g_a;
  var c:int = 16;
  var d:int_ptr = b - c;
  d[3] = a;
  var e:long_ptr = d[3];
  var f:long = 0L;
  e[0] = f;
  var g:int_ptr = d[3];
  var h:int = 1732584193;
  g[2] = h;
  var i:int_ptr = d[3];
  var j:int = -271733879;
  i[3] = j;
  var k:int_ptr = d[3];
  var l:int = -1732584194;
  k[4] = l;
  var m:int_ptr = d[3];
  var n:int = 271733878;
  m[5] = n;
}

function f_d(a:int, b:int, c:int) {
  var d:int = g_a;
  var e:int = 96;
  var f:int_ptr = d - e;
  g_a = f;
  f[23] = a;
  f[22] = b;
  f[21] = c;
  var g:long_ptr = f[23];
  var h:long = g[0];
  var i:long = 63L;
  var j:long = h & i;
  var k:int = i32_wrap_i64(j);
  f[3] = k;
  var l:int = f[21];
  var m:int = l;
  var n:long = i64_extend_i32_u(m);
  var o:long_ptr = f[23];
  var p:long = o[0];
  var q:long = p + n;
  o[0] = q;
  var r:int = 0;
  f[2] = r;
  loop L_b {
    var s:int = f[2];
    var t:int = f[21];
    var u:int = s;
    var v:int = t;
    var w:int = u < v;
    var x:int = 1;
    var y:int = w & x;
    if (eqz(y)) goto B_a;
    var z:int = f[22];
    var aa:int = f[2];
    var ba:ubyte_ptr = z + aa;
    var ca:int = ba[0];
    var da:int = f[23];
    var ea:int = 24;
    var fa:int = da + ea;
    var ga:int = f[3];
    var ha:int = 1;
    var ia:int = ga + ha;
    f[3] = ia;
    var ja:byte_ptr = fa + ga;
    ja[0] = ca;
    var ka:int = f[3];
    var la:int = 63;
    var ma:int = ka & la;
    if (ma) goto B_c;
    var na:int = 0;
    f[1] = na;
    loop L_e {
      var oa:int = f[1];
      var pa:int = 16;
      var qa:int = oa;
      var ra:int = pa;
      var sa:int = qa < ra;
      var ta:int = 1;
      var ua:int = sa & ta;
      if (eqz(ua)) goto B_d;
      var va:int = f[23];
      var wa:int = 24;
      var xa:int = va + wa;
      var ya:int = f[1];
      var za:int = 2;
      var ab:int = ya << za;
      var bb:int = 3;
      var cb:int = ab + bb;
      var db:ubyte_ptr = xa + cb;
      var eb:int = db[0];
      var fb:int = 255;
      var gb:int = eb & fb;
      var hb:int = 24;
      var ib:int = gb << hb;
      var jb:int = f[23];
      var kb:int = 24;
      var lb:int = jb + kb;
      var mb:int = f[1];
      var nb:int = 2;
      var ob:int = mb << nb;
      var pb:int = 2;
      var qb:int = ob + pb;
      var rb:ubyte_ptr = lb + qb;
      var sb:int = rb[0];
      var tb:int = 255;
      var ub:int = sb & tb;
      var vb:int = 16;
      var wb:int = ub << vb;
      var xb:int = ib | wb;
      var yb:int = f[23];
      var zb:int = 24;
      var ac:int = yb + zb;
      var bc:int = f[1];
      var cc:int = 2;
      var dc:int = bc << cc;
      var ec:int = 1;
      var fc:int = dc + ec;
      var gc:ubyte_ptr = ac + fc;
      var hc:int = gc[0];
      var ic:int = 255;
      var jc:int = hc & ic;
      var kc:int = 8;
      var lc:int = jc << kc;
      var mc:int = xb | lc;
      var nc:int = f[23];
      var oc:int = 24;
      var pc:int = nc + oc;
      var qc:int = f[1];
      var rc:int = 2;
      var sc:int = qc << rc;
      var tc:ubyte_ptr = pc + sc;
      var uc:int = tc[0];
      var vc:int = 255;
      var wc:int = uc & vc;
      var xc:int = mc | wc;
      var yc:int = f[1];
      var zc:int = 16;
      var ad:int = f + zc;
      var bd:int = ad;
      var cd:int = 2;
      var dd:int = yc << cd;
      var ed:int_ptr = bd + dd;
      ed[0] = xc;
      var fd:int = f[1];
      var gd:int = 1;
      var hd:int = fd + gd;
      f[1] = hd;
      continue L_e;
    }
    label B_d:
    var id:int = f[23];
    var jd:int = 8;
    var kd:int = id + jd;
    var ld:int = 16;
    var md:int = f + ld;
    var nd:int = md;
    f_e(kd, nd);
    var od:int = 0;
    f[3] = od;
    label B_c:
    var pd:int = f[2];
    var qd:int = 1;
    var rd:int = pd + qd;
    f[2] = rd;
    continue L_b;
  }
  label B_a:
  var sd:int = 96;
  var td:int = f + sd;
  g_a = td;
}

function f_e(a:int, b:int) {
  var c:int = g_a;
  var d:int = 48;
  var e:int_ptr = c - d;
  g_a = e;
  e[11] = a;
  e[10] = b;
  var f:int_ptr = e[11];
  var g:int = f[0];
  e[9] = g;
  var h:int_ptr = e[11];
  var i:int = h[1];
  e[8] = i;
  var j:int_ptr = e[11];
  var k:int = j[2];
  e[7] = k;
  var l:int_ptr = e[11];
  var m:int = l[3];
  e[6] = m;
  var n:int = 0;
  e[3] = n;
  loop L_b {
    var o:int = e[3];
    var p:int = 64;
    var q:int = o;
    var r:int = p;
    var s:int = q < r;
    var t:int = 1;
    var u:int = s & t;
    if (eqz(u)) goto B_a;
    var v:int = e[3];
    var w:int = 4;
    var x:int = v >> w;
    var y:int = 2;
    x > y;
    br_table[B_g, B_f, B_e, ..B_d](x)
    label B_g:
    var z:int = e[8];
    var aa:int = e[7];
    var ba:int = z & aa;
    var ca:int = e[8];
    var da:int = -1;
    var ea:int = ca ^ da;
    var fa:int = e[6];
    var ga:int = ea & fa;
    var ha:int = ba | ga;
    e[5] = ha;
    var ia:int = e[3];
    e[4] = ia;
    goto B_c;
    label B_f:
    var ja:int = e[8];
    var ka:int = e[6];
    var la:int = ja & ka;
    var ma:int = e[7];
    var na:int = e[6];
    var oa:int = -1;
    var pa:int = na ^ oa;
    var qa:int = ma & pa;
    var ra:int = la | qa;
    e[5] = ra;
    var sa:int = e[3];
    var ta:int = 5;
    var ua:int = sa * ta;
    var va:int = 1;
    var wa:int = ua + va;
    var xa:int = 15;
    var ya:int = wa & xa;
    e[4] = ya;
    goto B_c;
    label B_e:
    var za:int = e[8];
    var ab:int = e[7];
    var bb:int = za ^ ab;
    var cb:int = e[6];
    var db:int = bb ^ cb;
    e[5] = db;
    var eb:int = e[3];
    var fb:int = 3;
    var gb:int = eb * fb;
    var hb:int = 5;
    var ib:int = gb + hb;
    var jb:int = 15;
    var kb:int = ib & jb;
    e[4] = kb;
    goto B_c;
    label B_d:
    var lb:int = e[7];
    var mb:int = e[8];
    var nb:int = e[6];
    var ob:int = -1;
    var pb:int = nb ^ ob;
    var qb:int = mb | pb;
    var rb:int = lb ^ qb;
    e[5] = rb;
    var sb:int = e[3];
    var tb:int = 7;
    var ub:int = sb * tb;
    var vb:int = 15;
    var wb:int = ub & vb;
    e[4] = wb;
    label B_c:
    var xb:int = e[6];
    e[2] = xb;
    var yb:int = e[7];
    e[6] = yb;
    var zb:int = e[8];
    e[7] = zb;
    var ac:int = e[8];
    var bc:int = e[9];
    var cc:int = e[5];
    var dc:int = bc + cc;
    var ec:int = e[3];
    var fc:int = 66560;
    var gc:int = 2;
    var hc:int = ec << gc;
    var ic:int_ptr = fc + hc;
    var jc:int = ic[0];
    var kc:int = dc + jc;
    var lc:int = e[10];
    var mc:int = e[4];
    var nc:int = 2;
    var oc:int = mc << nc;
    var pc:int_ptr = lc + oc;
    var qc:int = pc[0];
    var rc:int = kc + qc;
    var sc:int = e[3];
    var tc:int = 66816;
    var uc:int = 2;
    var vc:int = sc << uc;
    var wc:int_ptr = tc + vc;
    var xc:int = wc[0];
    var yc:int = f_b(rc, xc);
    var zc:int = ac + yc;
    e[8] = zc;
    var ad:int = e[2];
    e[9] = ad;
    var bd:int = e[3];
    var cd:int = 1;
    var dd:int = bd + cd;
    e[3] = dd;
    continue L_b;
  }
  label B_a:
  var ed:int = e[9];
  var fd:int_ptr = e[11];
  var gd:int = fd[0];
  var hd:int = gd + ed;
  fd[0] = hd;
  var id:int = e[8];
  var jd:int_ptr = e[11];
  var kd:int = jd[1];
  var ld:int = kd + id;
  jd[1] = ld;
  var md:int = e[7];
  var nd:int_ptr = e[11];
  var od:int = nd[2];
  var pd:int = od + md;
  nd[2] = pd;
  var qd:int = e[6];
  var rd:int_ptr = e[11];
  var sd:int = rd[3];
  var td:int = sd + qd;
  rd[3] = td;
  var ud:int = 48;
  var vd:int = e + ud;
  g_a = vd;
}

function f_f(a:int) {
  var t:int;
  var b:int = g_a;
  var c:int = 96;
  var d:int_ptr = b - c;
  g_a = d;
  d[23] = a;
  var e:long_ptr = d[23];
  var f:long = e[0];
  var g:long = 63L;
  var h:long = f & g;
  var i:int = i32_wrap_i64(h);
  d[3] = i;
  var j:int = d[3];
  var k:int = 56;
  var l:int = j;
  var m:int = k;
  var n:int = l < m;
  var o:int = 1;
  var p:int = n & o;
  if (eqz(p)) goto B_b;
  var q:int = d[3];
  var r:int = 56;
  var s:int = r - q;
  t = s;
  goto B_a;
  label B_b:
  var u:int = d[3];
  var v:int = 120;
  var w:int = v - u;
  t = w;
  label B_a:
  var x:int = t;
  d[2] = x;
  var y:int = d[23];
  var z:int = d[2];
  var aa:int = 67072;
  var ba:int = aa;
  f_d(y, ba, z);
  var ca:int = d[2];
  var da:int = ca;
  var ea:long = i64_extend_i32_u(da);
  var fa:long_ptr = d[23];
  var ga:long = fa[0];
  var ha:long = ga - ea;
  fa[0] = ha;
  var ia:int = 0;
  d[1] = ia;
  loop L_d {
    var ja:int = d[1];
    var ka:int = 14;
    var la:int = ja;
    var ma:int = ka;
    var na:int = la < ma;
    var oa:int = 1;
    var pa:int = na & oa;
    if (eqz(pa)) goto B_c;
    var qa:int = d[23];
    var ra:int = 24;
    var sa:int = qa + ra;
    var ta:int = d[1];
    var ua:int = 2;
    var va:int = ta << ua;
    var wa:int = 3;
    var xa:int = va + wa;
    var ya:ubyte_ptr = sa + xa;
    var za:int = ya[0];
    var ab:int = 255;
    var bb:int = za & ab;
    var cb:int = 24;
    var db:int = bb << cb;
    var eb:int = d[23];
    var fb:int = 24;
    var gb:int = eb + fb;
    var hb:int = d[1];
    var ib:int = 2;
    var jb:int = hb << ib;
    var kb:int = 2;
    var lb:int = jb + kb;
    var mb:ubyte_ptr = gb + lb;
    var nb:int = mb[0];
    var ob:int = 255;
    var pb:int = nb & ob;
    var qb:int = 16;
    var rb:int = pb << qb;
    var sb:int = db | rb;
    var tb:int = d[23];
    var ub:int = 24;
    var vb:int = tb + ub;
    var wb:int = d[1];
    var xb:int = 2;
    var yb:int = wb << xb;
    var zb:int = 1;
    var ac:int = yb + zb;
    var bc:ubyte_ptr = vb + ac;
    var cc:int = bc[0];
    var dc:int = 255;
    var ec:int = cc & dc;
    var fc:int = 8;
    var gc:int = ec << fc;
    var hc:int = sb | gc;
    var ic:int = d[23];
    var jc:int = 24;
    var kc:int = ic + jc;
    var lc:int = d[1];
    var mc:int = 2;
    var nc:int = lc << mc;
    var oc:ubyte_ptr = kc + nc;
    var pc:int = oc[0];
    var qc:int = 255;
    var rc:int = pc & qc;
    var sc:int = hc | rc;
    var tc:int = d[1];
    var uc:int = 16;
    var vc:int = d + uc;
    var wc:int = vc;
    var xc:int = 2;
    var yc:int = tc << xc;
    var zc:int_ptr = wc + yc;
    zc[0] = sc;
    var ad:int = d[1];
    var bd:int = 1;
    var cd:int = ad + bd;
    d[1] = cd;
    continue L_d;
  }
  label B_c:
  var dd:long_ptr = d[23];
  var ed:long = dd[0];
  var fd:long = 3L;
  var gd:long = ed << fd;
  var hd:int = i32_wrap_i64(gd);
  d[18] = hd;
  var id:long_ptr = d[23];
  var jd:long = id[0];
  var kd:long = 3L;
  var ld:long = jd << kd;
  var md:long = 32L;
  var nd:long = ld >> md;
  var od:int = i32_wrap_i64(nd);
  d[19] = od;
  var pd:int = d[23];
  var qd:int = 8;
  var rd:int = pd + qd;
  var sd:int = 16;
  var td:int = d + sd;
  var ud:int = td;
  f_e(rd, ud);
  var vd:int = 0;
  d[0] = vd;
  loop L_f {
    var wd:int = d[0];
    var xd:int = 4;
    var yd:int = wd;
    var zd:int = xd;
    var ae:int = yd < zd;
    var be:int = 1;
    var ce:int = ae & be;
    if (eqz(ce)) goto B_e;
    var de:int = d[23];
    var ee:int = 8;
    var fe:int = de + ee;
    var ge:int = d[0];
    var he:int = 2;
    var ie:int = ge << he;
    var je:int_ptr = fe + ie;
    var ke:int = je[0];
    var le:int = 255;
    var me:int = ke & le;
    var ne:int = d[23];
    var oe:int = 88;
    var pe:int = ne + oe;
    var qe:int = d[0];
    var re:int = 2;
    var se:int = qe << re;
    var te:int = 0;
    var ue:int = se + te;
    var ve:byte_ptr = pe + ue;
    ve[0] = me;
    var we:int = d[23];
    var xe:int = 8;
    var ye:int = we + xe;
    var ze:int = d[0];
    var af:int = 2;
    var bf:int = ze << af;
    var cf:int_ptr = ye + bf;
    var df:int = cf[0];
    var ef:int = 65280;
    var ff:int = df & ef;
    var gf:int = 8;
    var hf:int = ff >> gf;
    var if:int = d[23];
    var jf:int = 88;
    var kf:int = if + jf;
    var lf:int = d[0];
    var mf:int = 2;
    var nf:int = lf << mf;
    var of:int = 1;
    var pf:int = nf + of;
    var qf:byte_ptr = kf + pf;
    qf[0] = hf;
    var rf:int = d[23];
    var sf:int = 8;
    var tf:int = rf + sf;
    var uf:int = d[0];
    var vf:int = 2;
    var wf:int = uf << vf;
    var xf:int_ptr = tf + wf;
    var yf:int = xf[0];
    var zf:int = 16711680;
    var ag:int = yf & zf;
    var bg:int = 16;
    var cg:int = ag >> bg;
    var dg:int = d[23];
    var eg:int = 88;
    var fg:int = dg + eg;
    var gg:int = d[0];
    var hg:int = 2;
    var ig:int = gg << hg;
    var jg:int = 2;
    var kg:int = ig + jg;
    var lg:byte_ptr = fg + kg;
    lg[0] = cg;
    var mg:int = d[23];
    var ng:int = 8;
    var og:int = mg + ng;
    var pg:int = d[0];
    var qg:int = 2;
    var rg:int = pg << qg;
    var sg:int_ptr = og + rg;
    var tg:int = sg[0];
    var ug:int = -16777216;
    var vg:int = tg & ug;
    var wg:int = 24;
    var xg:int = vg >> wg;
    var yg:int = d[23];
    var zg:int = 88;
    var ah:int = yg + zg;
    var bh:int = d[0];
    var ch:int = 2;
    var dh:int = bh << ch;
    var eh:int = 3;
    var fh:int = dh + eh;
    var gh:byte_ptr = ah + fh;
    gh[0] = xg;
    var hh:int = d[0];
    var ih:int = 1;
    var jh:int = hh + ih;
    d[0] = jh;
    continue L_f;
  }
  label B_e:
  var kh:int = 96;
  var lh:int = d + kh;
  g_a = lh;
}

function f_g(a:int, b:int, c:int) {
  var d:int = g_a;
  var e:int = 128;
  var f:int_ptr = d - e;
  g_a = f;
  f[31] = a;
  f[30] = b;
  f[29] = c;
  var g:int = 8;
  var h:int = f + g;
  var i:int = h;
  f_c(i);
  var j:int = f[31];
  var k:int = f[30];
  var l:int = 8;
  var m:int = f + l;
  var n:int = m;
  f_d(n, j, k);
  var o:int = 8;
  var p:int = f + o;
  var q:int = p;
  f_f(q);
  var r:int = f[29];
  var s:int = 8;
  var t:int = f + s;
  var u:int = t;
  var v:int = 88;
  var w:int = u + v;
  var x:int = 16;
  f_l(r, w, x);
  var y:int = 128;
  var z:int = f + y;
  g_a = z;
}

function f_h(a:int, b:int) {
  var c:int = g_a;
  var d:int = 16;
  var e:int_ptr = c - d;
  e[3] = a;
  e[2] = b;
  var f:ubyte_ptr = e[3];
  var g:int = f[0];
  var h:int = 255;
  var i:int = g & h;
  e[1] = i;
  var j:ubyte_ptr = e[2];
  var k:int = j[0];
  var l:byte_ptr = e[3];
  l[0] = k;
  var m:int = e[1];
  var n:byte_ptr = e[2];
  n[0] = m;
}

function f_i(a:int, b:int):int {
  var c:int = g_a;
  var d:int = 32;
  var e:int_ptr = c - d;
  g_a = e;
  e[7] = a;
  e[6] = b;
  var f:int = 16;
  e[5] = f;
  var g:int = 0;
  e[4] = g;
  var h:int = 0;
  e[3] = h;
  loop L_b {
    var i:int = e[3];
    var j:int = 256;
    var k:int = i;
    var l:int = j;
    var m:int = k < l;
    var n:int = 1;
    var o:int = m & n;
    if (eqz(o)) goto B_a;
    var p:int = e[3];
    var q:int = e[6];
    var r:int = e[3];
    var s:byte_ptr = q + r;
    s[0] = p;
    var t:int = e[3];
    var u:int = 1;
    var v:int = t + u;
    e[3] = v;
    continue L_b;
  }
  label B_a:
  var w:int = 0;
  e[2] = w;
  loop L_d {
    var x:int = e[2];
    var y:int = 256;
    var z:int = x;
    var aa:int = y;
    var ba:int = z < aa;
    var ca:int = 1;
    var da:int = ba & ca;
    if (eqz(da)) goto B_c;
    var ea:int = e[4];
    var fa:int = e[6];
    var ga:int = e[2];
    var ha:ubyte_ptr = fa + ga;
    var ia:int = ha[0];
    var ja:int = 255;
    var ka:int = ia & ja;
    var la:int = ea + ka;
    var ma:int = e[7];
    var na:int = e[2];
    var oa:int = e[5];
    var pa:int = na % oa;
    var qa:ubyte_ptr = ma + pa;
    var ra:int = qa[0];
    var sa:int = 255;
    var ta:int = ra & sa;
    var ua:int = la + ta;
    var va:int = 255;
    var wa:int = ua & va;
    e[4] = wa;
    var xa:int = e[6];
    var ya:int = e[2];
    var za:int = xa + ya;
    var ab:int = e[6];
    var bb:int = e[4];
    var cb:int = ab + bb;
    f_h(za, cb);
    var db:int = e[2];
    var eb:int = 1;
    var fb:int = db + eb;
    e[2] = fb;
    continue L_d;
  }
  label B_c:
  var gb:int = 0;
  var hb:int = 32;
  var ib:int = e + hb;
  g_a = ib;
  return gb;
}

function f_j(a:int, b:int, c:int, d:int):int {
  var e:int = g_a;
  var f:int = 32;
  var g:{ a:int, b:int, c:int, d:int, e:int, f:int, g:int, h:int } = 
    e - f;
  g_a = g;
  g.h = a;
  g.g = b;
  g.f = c;
  g.e = d;
  var h:int = 0;
  g.d = h;
  var i:int = 0;
  g.c = i;
  var j:int = 0;
  g.b = j;
  loop L_b {
    var k:int = g.b;
    var l:int = g.f;
    var m:int = k;
    var n:int = l;
    var o:int = m < n;
    var p:int = 1;
    var q:int = o & p;
    if (eqz(q)) goto B_a;
    var r:int = g.d;
    var s:int = 1;
    var t:int = r + s;
    var u:int = 256;
    var v:int = t % u;
    g.d = v;
    var w:int = g.c;
    var x:int = g.h;
    var y:int = g.d;
    var z:ubyte_ptr = x + y;
    var aa:int = z[0];
    var ba:int = 255;
    var ca:int = aa & ba;
    var da:int = w + ca;
    var ea:int = 256;
    var fa:int = da % ea;
    g.c = fa;
    var ga:int = g.h;
    var ha:int = g.d;
    var ia:int = ga + ha;
    var ja:int = g.h;
    var ka:int = g.c;
    var la:int = ja + ka;
    f_h(ia, la);
    var ma:int = g.h;
    var na:int = g.h;
    var oa:int = g.d;
    var pa:ubyte_ptr = na + oa;
    var qa:int = pa[0];
    var ra:int = 255;
    var sa:int = qa & ra;
    var ta:int = g.h;
    var ua:int = g.c;
    var va:ubyte_ptr = ta + ua;
    var wa:int = va[0];
    var xa:int = 255;
    var ya:int = wa & xa;
    var za:int = sa + ya;
    var ab:int = 256;
    var bb:int = za % ab;
    var cb:ubyte_ptr = ma + bb;
    var db:int = cb[0];
    var eb:int = 255;
    var fb:int = db & eb;
    g.a = fb;
    var gb:int = g.a;
    var hb:int = g.g;
    var ib:int = g.b;
    var jb:ubyte_ptr = hb + ib;
    var kb:int = jb[0];
    var lb:int = 24;
    var mb:int = kb << lb;
    var nb:int = mb >> lb;
    var ob:int = gb ^ nb;
    var pb:int = g.e;
    var qb:int = g.b;
    var rb:byte_ptr = pb + qb;
    rb[0] = ob;
    var sb:int = g.b;
    var tb:int = 1;
    var ub:int = sb + tb;
    g.b = ub;
    continue L_b;
  }
  label B_a:
  var vb:int = 0;
  var wb:int = 32;
  var xb:int = g + wb;
  g_a = xb;
  return vb;
}

function f_k(a:int, b:int, c:int, d:int):int {
  var e:int = g_a;
  var f:int = 272;
  var g:int_ptr = e - f;
  g_a = g;
  g[67] = a;
  g[66] = b;
  g[65] = c;
  g[64] = d;
  var h:int = g[67];
  var i:int = g;
  f_i(h, i);
  var j:int = g;
  var k:int = g[66];
  var l:int = g[65];
  var m:int = g[64];
  f_j(j, k, l, m);
  var n:int = 0;
  var o:int = 272;
  var p:int = g + o;
  g_a = p;
  return n;
}

function f_l(a:int, b:int, c:int) {
  var d:int = g_a;
  var e:int = 16;
  var f:{ a:int, b:int, c:int, d:int } = d - e;
  f.d = a;
  f.c = b;
  f.b = c;
  var g:int = 0;
  f.a = g;
  loop L_b {
    var h:int = f.a;
    var i:int = f.b;
    var j:int = h;
    var k:int = i;
    var l:int = j < k;
    var m:int = 1;
    var n:int = l & m;
    if (eqz(n)) goto B_a;
    var o:int = f.c;
    var p:int = f.a;
    var q:ubyte_ptr = o + p;
    var r:int = q[0];
    var s:int = f.d;
    var t:int = f.a;
    var u:byte_ptr = s + t;
    u[0] = r;
    var v:int = f.a;
    var w:int = 1;
    var x:int = v + w;
    f.a = x;
    continue L_b;
  }
  label B_a:
}

