version: "3"
services:
    calc:
        build: .
        ports:
            - "10006:3000"
        restart: always
        tty: true
        stdin_open: true
        environment:
            - FLAG=ping{FAKE}
