version: '2.4'
services:
  nginx:
    image: nginx:1.20.1
    ports:
      - "0.0.0.0:61616:61616"
    restart: always
    volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - internal_network
      - out_network
  strangeport:
    build: ./
    restart: always
    networks:
      - internal_network
networks:
    internal_network:
        internal: true
        ipam:
            driver: default
    out_network:
        ipam:
            driver: default
