version: '3.7'
services:
  web:
    build:
      context: web
    image: vault_web
    volumes:
      - ./web:/app
    # environment:
    #   - FLAG=...
    #   - PUBLIC_HOST=...
    init: true
  nginx:
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 11223:80
    depends_on:
      - web
